### ISSUE TITLE
Allow configuration of context id pattern

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-lab#100]
Allow configuration of context id pattern.

**Comment by reckart** [comment]
@Horsmann 

Can be done now by placing a configuration file into `${DKPRO_HOME}/org.dkpro.lab/settings.properties` with the content

```
context-id-pattern={0}-{1}-{2}
```

Where the `{x}` get replaced with:

* `0` - short task name
* `1` - timestamp `yyyyMMddHHmm`
* `2` - the UUID

**Comment by Horsmann** [comment]
Thanks. Can I set this flag also programatically? This is something I would want to set as new default value for TC experiments rather than having always a property file created by the user.

**Comment by reckart** [comment]
Presently not. You'd have to add a setter for that on the respective bean. However, if you programmatically set it, then you would override the explicit preferences from the user, which would IMHO not be a good idea. 

I think it should be up to the user to define what pattern should be used.

**Comment by Horsmann** [comment]
In this particular case I would still set it. I have heard from several users that they feel confused by the UUID as they expect it to behave like a timestamp but it doesn't.  Furthermore, it really makes reading through a folder full of folders quite exhausting.. :)

When/Where do I have to  setting beans programmatically?
TaskContext.setProperty() doesn't exist?

**Comment by reckart** [comment]
Well, if this is a popular user demand, then let's change the default value of the pattern property in the context.xml / test-context.xml. 

Regarding programmatically setting this, you'd have to add the `setContextIdPattern()` setter and then do something like this:

```
	    ((DefaultTaskContextFactory) Lab.getInstance().getTaskContextFactory()).setContextIdPattern(...);
```

**Comment by Horsmann** [comment]
Setting the default would be my preferred solution :D - most people can easier deal with a timestamp than with an UUID in terms of human-readability.

**Comment by reckart** [comment]
You could also add a higher-resolution timestamp and try using that instead of the UUID. I didn't do that because I was afraid that two context could be created at virtually the same time and there would be a clash with the IDs. You could try circumventing that by making nextId() synchronized and remembering the last issued timestamp, and if necessary wait 1ms before issuing the next one.

**Comment by reckart** [comment]
Btw. if I needed a timestamp, I simply sorted the context folders by their file creation timestamp. I never felt that this info needed to be included in the name.

**Comment by Horsmann** [comment]
I run often 10fold CVs with in parameter search experiments (factor *N) on our compute server. Sometimes I need to have a look into the training data folder, sometimes elsewhere - if you do that on a command line having this as part of the name is extremely helpful. There are several work-arounds for that but needing no workaround at all is better :)

I think for the TC setup which I have in mind here experimentname + timestamp should suffice to keep things unique. You can extend the timestamp to milliseconds this should further lower the likeliness of this threat?

**Comment by reckart** [comment]
You can do it. However, I would recommend synchronizing the nextId() method and adding an explicit check like 

```
newTimestamp = now;
while (newTimestamp <= oldTimestamp) {
  // do nothing or wait 1ms
}
```

**Comment by reckart** [comment]
I'd catch and ignore it. The exceptions that wait() throws are one of the very few cases where IMHO swallowing an exception is perfectly fine.
