### ISSUE TITLE
Missing artifact org.springframework:spring-asm:jar:4.1.9.RELEASE

### ISSUE THREAD

**Issue by maxxkia** [dkpro/dkpro-lab#102]
The dependency `spring-asm:4.1.9.RELEASE` in master [pom.xml](https://github.com/dkpro/dkpro-lab/blob/master/pom.xml) cannot be resolved. The latest release of this artifact is version `3.2.0.M1`:
https://mvnrepository.com/artifact/org.springframework/spring-asm

**Comment by maxxkia** [comment]
I think this dependency is not even used anywhere. It should be deleted. I noticed this problem in a project where I added a dependency on dkpro-lab 0.13.0.

**Comment by reckart** [comment]
This dependency is not declared in any `dependency` section, only in the `dependencyManagement` section, right? And DKPro Lab is not using Spring 4, it is using Spring 3. If you are using DKPro Lab in a Spring 4 context, you may have to override some dependencies. IMHO that is to be expected and not really a bug.

**Comment by maxxkia** [comment]
@reckart 
- Well, first of all if it doesn't need this dependency why should it be declared in the dependency management.
- and, it's using 4.1.9.RELEASE [look here](https://github.com/dkpro/dkpro-lab/blob/master/pom.xml#L39)
- also, my project is not a Spring based project, but I'm using DKPro TC and DKPro Lab both of which are Spring projects. The problem starts from the point that DKPro TC uses Spring 3 and this dependency declaration for spring-asm inside DKPro Lab pom file causes `mvn package` fail because there's no such `spring-asm:4.1.9.RELEASE`

So at the end I was forced to have this ugly [import](https://github.com/openminted/uc-tdm-socialsciences/blob/master/ss-variable-detection/pom.xml#L60) in my project; which excludes the faulty spring-asm dependency from DKPro Lab.

**Comment by reckart** [comment]
Ok, so DKPro Lab uses Spring 4. Indeed we should remove the entry from the dependency management. However, I'm afraid that this won't remove the problem root. Having a dependency in the  `dependencyManagement` section doesn't actually add the dependency - it only defines the version. So the question would remain: why does this dependency appear in your set of transitive dependencies at all? If you remove the exclude and check the dependency hierarchy, can you see how this dependency is dragged in?

**Comment by maxxkia** [comment]
it's coming from dkpro-lab-core
![hierarchy](https://user-images.githubusercontent.com/6916434/30651870-2dd92d90-9e27-11e7-9b96-2d5a702cf7ca.png)

**Comment by reckart** [comment]
Something is strange here. The `develop` branch still uses Spring 3. Normally, no changes should be committed to the master branch. Rather the develop branch should be merged in regular intervals into master. I need to check what happened here...

**Comment by reckart** [comment]
Apparently I bumped the Spring version when I tried giving the DKPro Lab UIMA-AS module a refresh in commit 402837b5d22b71eb18ca6f118a6c8899efbbf5bb.

Later, DKPro Lab was reverted to Spring 3 in commit 349d0bfa73f1f2ff5a9e5433d96caa3e58d43e11 - but that seems to have happened after the 0.13.0 release. 

So looks like 0.13.0 was released with the wrong Spring version.

@Horsmann do you have any opinion on this? Should we upgrade DKPro Lab to Spring 4 (as in 0.13.0) or leave it at the same Spring version also used in DKPro Core and uimaFIT (namely 3.2.16.RELEASE)?

**Comment by Horsmann** [comment]
I would want to keep spring versions aligned. For TC releases I use as `master` version of Spring whatever the latest core releases uses. If you plan to update to 4 for the next release the we should use 4 in Lab too. I will adapt TC accordingly

**Comment by reckart** [comment]
DKPro Core is currently using what uimaFIT is using and uimaFIT is using the lowest Spring version that it needs to actually work.

I'd kind of tend to stay at Spring 3 in DKPro Core. I personally use Spring 4 in web apps nowadays, but since Spring 4 is backwards compatible, I haven't run into problems so far embedding DKPro Core/uimaFIT even there (except maybe the occasional manual dependency override/exclude).

**Comment by Horsmann** [comment]
I personally wouldn't mind to make a new release of Lab with the current changes and the new/corrected spring version 3 ~

**Comment by reckart** [comment]
@maxxkia could you check building against 0.14.0-SNAPSHOT?

**Comment by maxxkia** [comment]
I still have this problem because `dkpro-tc:0.9.0` depends on `dkpro-lab:0.13.0`. Probably if I also switch to `dkpro-tc:1.0.0-SNAPSHOT` this would be resolved.

**Comment by maxxkia** [comment]
Ok, now I switched to `dkpro-tc:1.0.0-SNAPSHOT`but the problem is still not resolved. Now maven is complaining that it can't find `spring-asm:3.2.16.RELEASE`. Again there's no such version of `spring-asm` the latest release is `3.2.0.M1`

**Comment by reckart** [comment]
In the dependency hierarchy screenshot you posted above, it is visible that you are trying to use `spring-context:3.1.2.RELEASE`. Make sure that all your Spring dependencies have the same version. You can do that by adding a `dependencyManagement` section to your POM, and adding all your transitive Spring dependencies there with the specific version that you want to use. Recent versions of `spring-context`should no longer try to drag in `spring-asm`. 

We'll remove `spring-asm` from the `dependencyManagement` section in DKPro Lab, but it will not fix your problem. Managing the Spring dependencies in your own POM to a certain version will fix your problem.

**Comment by maxxkia** [comment]
Right. I think I this dependency is actually coming from another library I'm depending on probably CERMINE.
