### ISSUE TITLE
DKPro Lab Release 0.14.0

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-lab#107]
I am planning to release 0.14.0 soon. 

@reckart is there anything that should prevent a release in the near time?

**Comment by reckart** [comment]
I think I already update and check dependencies recently - but maybe that should be double-checked. Otherwise, I think there is no obstacle.

**Comment by Horsmann** [comment]
@reckart can the `ml-example` project be excluded from the release? i.e. setting `maven.deploy.skip` ?

**Comment by reckart** [comment]
In principle yes, but why?

**Comment by Horsmann** [comment]
why would you want to release examples ? I have no general objection against it but it doesn't serve much purpose? The TC example project is excluded from a release, so I assumed this example project should also be excluded?

**Comment by reckart** [comment]
It is fine by me. I was wondering if you had specific reasons like that it might create circular dependencies or other types of problems. But I agree, deploying it to Maven Central is not particularly useful.

**Comment by Horsmann** [comment]
Here is the release candidate: https://oss.sonatype.org/content/repositories/orgdkpro-1031
@reckart how much time do you need to take a look (if you even want to?)

**Comment by reckart** [comment]
I'll try to have a look at it over the weekend.

**Comment by reckart** [comment]
I think we are good for a release.
