### ISSUE TITLE
Allow creation of dimension bundles that have no name

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dkpro/dkpro-lab#66]
```
If the name is not used anywhere else and users do not really need to
reference a bundle over the name then - yes - anonymous bundles would
be good.

```

Original issue reported on code.google.com by `richard.eckart` on 6 Aug 2014 at 11:12

**Comment by reckart** [comment]
This should be fixed by 085b0ee230f6cec23a813b5825f0a5a16c44c442 which I though had no associated issue
