### ISSUE TITLE
getStorageLocation() always returns a folder

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dkpro/dkpro-lab#70]
```
TaskContext.getStorageLocation() always creates/returns a folder. But 
sometimes, I just want to create a file, not a full folder. It would be nice to 
have a getStorageFile() and getStorageFolder() instead and to deprecate the 
getStorageLocation().
```

Original issue reported on code.google.com by `richard.eckart` on 19 Jan 2015 at 1:48

**Comment by reckart** [comment]
The methods getFolder() and getFile() are present now.

**Comment by reckart** [comment]
getFolder() is not backwards compatible with getStorageLocation() - the old behavior should be restored for backwards compatibility.
