### ISSUE TITLE
Improve Latex mode of FlexTable

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-lab#78]
Improve Latex mode of FlexTable - the code is only half-done right now.

**Comment by reckart** [comment]
@mwunderlich If I see it correctly, your changes to the Latex writing may have a side effect on the table in that it may transpose the full table contents. That doesn't seem like a good idea, e.g. if the same table is written twice in a row with transpose turned on. Could we fix that in some way? E.g. such that instead of transposing the table data, only transposed data is written? Or simply such that the "transpose" argument to getLatexWriter() is removed forcing the user to call transpose() explicitly if desired?

**Comment by mwunderlich** [comment]
@reckart Thanks for the hint, Richard. If I understand correctly, the problem is that the transposed table is persisted in the model, so if the Report is run twice, the second time it would write the original table. Also, if other reports come after the Latex report, they would work with the transposed version. That would be a problem, of course. I will change it, so that the transposed data is only kept temporarily.

**Comment by reckart** [comment]
@mwunderlich FlexTable instances are not shared between reports. It is more a concern with the API itself. If I do this:

    writer w = table.getWriter(transpose=true);

then I expect that w gets a transposed view but table remains the same.

If I do this:

    table.transpose()
    writer w = table.getWriter()

then it is clear that transpose() applies to the table as a whole and not to the writer.

I think removing the transpose parameter from getLatexWriter() would be the simplest option and it would resolve any concerns about unforeseen side-effects.

**Comment by mwunderlich** [comment]
Hi Richard, 

ok, I got your point. I have just made the required changes and also added a getLatexWriter() without parameters which provides a default. The changes are committed in my fork (ecc752d16e02839fef29ea0da71cde36c97a23f3) - hopefully with correct DKPro styling this time. :)

Cheers, 

Martin

**Comment by reckart** [comment]
I have cherry-picked your changes over into the develop branch resisting the idea to merge and get lots of "duplicate/replayed" commits in the process.

**Comment by mwunderlich** [comment]
Great, thanks, Richard. 
The fork and branches should be in synch again now, but it makes sense to cherrypick to avoid unwanted commits. 

Cheers, 

Martin

**Comment by mwunderlich** [comment]
Can we close this issue?

**Comment by reckart** [comment]
I guess. Closing - if anybody feels different, please reopen and explain. Thanks Martin!
