### ISSUE TITLE
BatchReportBase.getSubtaskContextIds() returns NPE

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-lab#83]
In BatchReportBase.getSubtaskContextIds() 

```java
getProperties().get(BatchTask.SUBTASKS_KEY);
```
returns null under certain circumstances (I haven't found out yet, when and why), maybe always. At least this is what happens when used with a DefaultBatchTask (e.g. in DKPro TC). To reproduce, run one of the TC demos.

**Comment by zesch** [comment]
I can reproduce the problem, but have no idea where it comes from ...

2015-09-02 19:22 GMT+02:00 Johannes Daxenberger <notifications@github.com>:

**Comment by daxenberger** [comment]
The underlaying cause in ReportBase is that the PropertiesAdapter returns an empty map. This must have been working before but now it doesn't.

**Comment by reckart** [comment]
Did the batch task actually execute any subtasks?

**Comment by zesch** [comment]
I just verified: yes it does.

2015-09-02 20:46 GMT+02:00 Richard Eckart de Castilho <
notifications@github.com>:

**Comment by daxenberger** [comment]
Subtasks are correctly executed; however, none of the PROPERTIES.txt files contain any information on subtasks. I don't know whether this is different from before the changes in DKPro Lab.

**Comment by reckart** [comment]
Which test in DKPro TC is failing on this?

**Comment by daxenberger** [comment]
Almost all tests in the example modules. E.g. de.tudarmstadt.ukp.dkpro.tc.examples.single.document.TwitterSentimentDemo

**Comment by reckart** [comment]
I've taken a look at that yesterday and it should be fixed by https://github.com/dkpro/dkpro-lab/issues/84 - I also made updates in TC to accommodate for the changes. However, then I hit https://github.com/dkpro/dkpro-tc/issues/273 . Can you have a look and comment if this is more likely a TC or a Lab issue? I'd currently see it as a TC issue, hence I opened the issue over there.

**Comment by reckart** [comment]
Hum... I should not have opened #84 - we already had this issue... *sigh*.

Duplicates #84.
