### ISSUE TITLE
dkpro-lab release 0.12.0

### ISSUE THREAD

**Issue by maxxkia** [dkpro/dkpro-lab#90]
Since we have discussed making a new release for dkpro-lab, I assume I need commit access to this repository for updating the version in pom file.

**Comment by reckart** [comment]
Added @maxxkia to dev team.

**Comment by maxxkia** [comment]
Thanks.
Short question, we don't plan to fix/close any of the current open issues for release 0.12.0, right? I assume this release is mainly for the change in groupid.

**Comment by reckart** [comment]
We have 15 issues resolved for 0.12.0: https://github.com/dkpro/dkpro-lab/issues?utf8=✓&q=is%3Aissue+milestone%3A0.12.0+is%3Aclosed+

The groupId/package change was actually an afterthought since we were looking for the right Sonatype issue to look for MC publishing permissions.

**Comment by maxxkia** [comment]
- [ ] Merge Development branch with Master branch
- [ ] Run build and Deploy artifacts to maven central repository

**Comment by Horsmann** [comment]
Will it take you long until you can release Lab?

**Comment by reckart** [comment]
It's already been staged. We are doing the final checks before actually promoting it to Maven Central.

**Comment by maxxkia** [comment]
I think it has passed the evaluations in staging repository and is waiting for approval to be released to maven central
https://oss.sonatype.org/content/repositories/orgdkpro-1011/

**Comment by reckart** [comment]
I had a quick check of the artifacts. License and notice files in code module, JAR signatures.

We have the "doc" module included, which doesn't need to be deployed to Maven Central (#94). I have excluded it now from being deployed.  The change is already available on the master branch.

Please drop the staged release and redo. This time, when you look at the staged repo, the folder for the doc module should no longer be there.

**Comment by maxxkia** [comment]
Thanks for making this fix.

I ran another build and uploaded the new artifacts to Nexus repository. Artifacts passed the evaluation and are again waiting for your approval:
https://oss.sonatype.org/content/repositories/orgdkpro-1012/

**Comment by reckart** [comment]
Testing a build of DKPro TC against the staged repo...

**Comment by reckart** [comment]
... test build successful.

+1 to release the staged DKPro Lab  0.12.0 to Maven Central.

**Comment by maxxkia** [comment]
How many **OK**s should we receive till we proceed with releasing to Maven Central repo?

Do we have any specific procedure for this?

**Comment by reckart** [comment]
No formal procedure. If you are ok and I am ok. I think we are fine. We could have involved @Horsmann to do a check of the release against TC, but I did that for him. So I think we are good for promotion.

**Comment by Horsmann** [comment]
Please release :) & thanks

**Comment by maxxkia** [comment]
Ok, I finalized the release. It's now deployed to Sonatype local repository, I assume it might take some time to show up in the Maven Central.
