### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-lab#92]
Upgrade dependencies including but maybe not limited to

- [x] UIMA -> 2.8.1
- [x] uimaFIT -> 2.2.0 (still unreleased, but RC under review)
- [x] Spring -> 3.2.16
- [X] plugin dependencies
- [x] DKPro parent POM 14

**Comment by maxxkia** [comment]
@reckart 
in my previous commit I upgraded several dependencies two of which are _major version_ upgrades:
- fop 0.95 -> 2.1
- commons-math 2.1 -> commons-math3 3.6.1
After these changes project build was successful. I assume there will be no side effects.

**Comment by reckart** [comment]
commons-math3 has different package names as well, so that would require changes to the code/imports. I think you didn't do this, so I think the code still works only because we have a transitive dependency on math 2.1 somewhere. So the code should be updated to use math3.

Regarding fop - it would be good to test this. 

@daxenberger do you have example reports in TC that render to PDF?

**Comment by daxenberger** [comment]
> do you have example reports in TC that render to PDF?

Not PDF, only latex (using org.dkpro.lab.reporting.FlexTable...)

**Comment by reckart** [comment]
I have removed the commons-math dependency - it was used nowhere.

Didn't get round to checking if the new FOP version still works ok.

**Comment by maxxkia** [comment]
@reckart Latest updates to the code (including dependency upgrades) are in develop branch. Should they be merged with Master branch so they can be tested in DKPro-TC or this is not necessary?

**Comment by reckart** [comment]
@maxxkia Jenkins builds on the development branch. The changes need only be merged over to master before the release. The release should be made on the master branch.

**Comment by reckart** [comment]
@maxxkia FOP upgrade approved. Please continue.
