### ISSUE TITLE
Introduce a conversion service - allow registering special discriminator handlers

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-lab#96]
Add a conversion service for registering discriminator handles.

**Comment by Horsmann** [comment]
A conversion service has been added.
The conversion service is at the moment accessed after the old behavior and overriding entries if there is anything in the conversion service for a discriminator. 
Test cases are still missing.
Together with this TC commit https://github.com/dkpro/dkpro-tc/commit/f781cd122f00d3fbaa166eb72aa6565c574b1aa1 I have the desired behavior. 
@reckart Mind to take a look? Probably not exactly what you had in mind?

**Comment by reckart** [comment]
At a first look, that looks pretty much the way that I had imagined it. It would be possible to do it in a more sophisticated way, but this was basically what I had in mind for the first throw.

The huge number of unrelated changes in the commit make it a bit difficult to see the exact differences. Would be great if you could check the changes before you commit and avoid committing large amounts of whitespace/formatting changes separately from functional changes.

**Comment by Horsmann** [comment]
Okay thanks. From my side this is all complexity that I need. So unless you want to add something I would close this one?

**Comment by reckart** [comment]
Nothing to add - no objections against closing the issue.
