### ISSUE TITLE
Attributes are reinitialized during Task analysis step

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-lab#97]
The `TaskBase` reinitializes the arrays for `discriminators` and `properties`  in the `analyze()` method.

In case discriminators or properties have been registered before the task runs those registered values are lost.

**Comment by reckart** [comment]
They must be reinitialized at some point because the tasks are re-used.

**Comment by Horsmann** [comment]
Hm, when I register something before lab runs I probably want it to be still there when the task is being reused? I would need to distinguish between system-registered attributes which probably should be reseted and user-generated ones that shall be preserved ?

**Comment by reckart** [comment]
You'd have to play around a bit with this idea. I could imagine analyze() filling a second internal map and when doing a lookup with getAttributes() or getAttribute() it could first check that internal map and then the other attributes map...

**Comment by Horsmann** [comment]
I see two possibilities for implementing this:

a) Introduce a `global` flag meaning this is an attribute that shall be sustained across reinitialization. I would store these attributes then in an own map. When calling `getAttributes()` you would receive a combination of both maps. `Problem: ` what to do if a key exist in both maps.

b) Make an own set of `set/getAttributes()` which is intended only for internal usage and one for user-defined input e.g. `set/getUserDefinedAttributes()`. This would probably solve the double-key issue but you would additional setter/getter methods and an additional file on the disc `ATTRIBUTES_USER.txt` (consequently then also `ATTRIBUTES_LAB.txt`)

Thoughts on this?

**Comment by reckart** [comment]
local overrides global

**Comment by reckart** [comment]
Actually, I don't think that we multiple getters and so on. The problem you describe is that analyze() overrides the properties, right?

So instead of overriding the field "properties" in analyze, fill in another second map, e.g. "analyzedProperties". When getProperties() or getProperty() are called, then first look in the `analyzedProperties` - if nothing is there, then look in the `properties` - if nothing is there, return null.

**Comment by reckart** [comment]
I think a single ATTRIBUTES.txt file is sufficient and it should contain the "actual" attributes, i.e. the result from getAttributes() - no separate `ATTRIBUTES_LAB` and `ATTRIBUTES_USER`.

**Comment by reckart** [comment]
Btw. to prevent leaking information between Task runs, it would probably be a good idea to throw an exception if setAttribute() is called *after* a task has been executed for the first time. I.e. the "user-set attributes" must remain the same across all runs.

**Comment by Horsmann** [comment]
how do I figure out if a Task did already run?

**Comment by Horsmann** [comment]
I introduced a flag which is set in the execution engine. This should do the trick.

**Comment by daxenberger** [comment]
Looks good to me.

**Comment by reckart** [comment]
I think that flag should be set not in the execution engine by in DefaultLifeCycleManager.initialize() - in that way we also do not have to change *all* execution engines to set the flag.

**Comment by Horsmann** [comment]
@reckart this seems to be the wrong place. The `nested` test cases all fail when I relocated setting the flag into `DefaultLifeCycle`. `setAttribute()` is called again after a task was executed.

**Comment by Horsmann** [comment]
I am not entirely sure what the problem is but it seems like the outer task is set to `already executed` before all `inner task` finished and then runs into the newly introduced exception when re-setting some values.

**Comment by reckart** [comment]
The outer task starts executing before the inner tasks start and it ends after the inner tasks end. They are called "nested tasks" after all ;)

**Comment by reckart** [comment]
I'm not sure *when* you try to set attributes...? When do you do it and for which purpose?

**Comment by Horsmann** [comment]
I am not setting anything that is lab that passes through this information when the task is already marked as executed:
Key: `Subtasks`
Value: `[ConfigDumperTask1-4e48a225-7c11-11e6-9aaa-77a6215c46f5, ConfigDumperTask1-4e4e6e86-7c11-11e6-9aaa-77a6215c46f5, ConfigDumperTask1-4e53ecc7-7c11-11e6-9aaa-77a6215c46f5]`

When I relocate setting the `markExecuted()` into the `DefaultLifeCycle` class as you suggested the flag is already set to `true` and this `setAttributes` call is then rejected.
If you set in the executionEngine this issue does not arise.

**Comment by reckart** [comment]
Ok, I see. The BatchTaskEngine uses setAttribute to record the subtasks. My assumption was that setAttribute was so far never called by Lab code but only by "user" code. In that case, we probably really do need an additional setter. I would suggest "setTransientAttribute(String, String)" which would add a key to the analyzedAttributes map. BatchTaskEngine would use setTransientAttribute then instead of setAttribute.

**Comment by reckart** [comment]
Btw. I see that you also introduced the separation between analyzed an "static" discriminators. I am not sure that makes sense... do you have an actual use case for this or was it just for synchronicity?

**Comment by Horsmann** [comment]
I didn't see why discriminators should be different. They had the same problem that if any would have been provided manually the analyse step would have thrown that away like for the attributes. So I copied everything I did for attributes to the discriminators. I have no use cases for that but it seemed to be wrong here too.

**Comment by reckart** [comment]
My intuition was that discriminators are always obtained from the parameter space and never set manually. Actually I am not sure if we need a setDiscriminator() method at all. That is why I asked if you had a use case.

**Comment by Horsmann** [comment]
Does not look like it has been used. I removed it.
