### ISSUE TITLE
Naming inconsistencies properties vs attributes

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-lab#98]
The 'TaskBase' uses since some time a method called `get/setAttributes` while variables and the file that is written to disc are still called `properties`.

The `ReportBase` is also still using properties. 

The names should be adapted to `attribute` and the file written to disc should be called consequently `ATTRIBUTES.txt`, too.

**Comment by reckart** [comment]
As a historical note: "property" was renamed to "attribute" because "property" is kind of a reserved name in Groovy.
