### ISSUE TITLE
DKPro Lab Release 0.13.0

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-lab#99]
Perform release of `0.13.0`

- [x] Draft the release 
- [x] Announce release
- [x] Resync `develop` branch to use `0.14.0-SNAPSHOT`

**Comment by Horsmann** [comment]
Release performed

**Comment by reckart** [comment]
So now we should have a look at the staging repo?

**Comment by Horsmann** [comment]
Oh - I already released it actually. :/

**Comment by reckart** [comment]
;) Can you please also update the `_data/releases.yml` file on the gh-pages branch for the new version?

**Comment by Horsmann** [comment]
Updated.
